### ISSUE TITLE
Error at IPV6

### ISSUE THREAD

**Issue by Lzaruss** [ruinaigelreogo/whatismyip#4]
Hello, i just tried ur page and i realize that the ipv6 has a error: 
![image](https://user-images.githubusercontent.com/104428151/213213737-44bd22b0-ca77-4c84-9a26-2687be875fe1.png)

Your page give me the same ip for both.

**Comment by ttylnpm** [comment]
> Hello, i just tried ur page and i realize that the ipv6 has a error: ![image](https://user-images.githubusercontent.com/104428151/213213737-44bd22b0-ca77-4c84-9a26-2687be875fe1.png)
> 
> Your page give me the same ip for both.

Oh. That error is caused by The API I was using. The IPV6 works sometimes. Check the Javascript file.
